// Get all contacts - render
GET https://cse341-t68c.onrender.com/contacts

//Get contact by ID - render

GET https://cse341-t68c.onrender.com/contacts/6aa0d5033cdcb7a7405cc291

//Get all contacts - local
GET http://localhost:3000/contacts

//Get contact by Id - local
GET http://localhost:3000/contacts/6aa0d5033cdcb7a7405cc291


 //Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Isama",
    "email": "mary.isama@example.com",
    "favoriteColor": "Pink",
    "birthday": "1998-01-01"
}


//Delete contact
DELETE http://localhost:3000/contacts/contactID